# Generated by Django 4.2.27 on 2026-01-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('SUPERVISOR', 'Superviseur'), ('OPERATOR', 'Opérateur'), ('ANALYST', 'Analyste'), ('REGULATOR', 'Autorités/Gouvernement')], default='OPERATOR', max_length=50),
        ),
    ]
