# Generated by Django 4.2.27 on 2026-02-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_regulator_to_mmg'),
        ('accounts', '0003_user_phone_user_profile_photo_user_updated_at'),
    ]

    operations = [
    ]
