# Generated by Django 4.2.27 on 2026-02-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20260203_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur Système'), ('SUPERVISOR', 'Gestionnaire de Site'), ('OPERATOR', 'Technicien/Opérateur'), ('ANALYST', 'Analyste'), ('OWNER', 'Propriétaire/Décideur'), ('MMG', 'Autorité (MMG)')], default='OPERATOR', max_length=50),
        ),
    ]
