# Generated by Django 4.2.27 on 2026-02-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_sites', '0002_miningsite_code_miningsite_concession_geojson_and_more'),
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_sites',
            field=models.ManyToManyField(blank=True, help_text='Sites auxquels cet utilisateur a accès. Vide = aucun accès site (sauf ADMIN).', related_name='assigned_users', to='mining_sites.miningsite', verbose_name='Sites assignés'),
        ),
    ]
