# Generated by Django 4.2.27 on 2026-02-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_assigned_sites_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur de la plateforme'), ('SITE_MANAGER', 'Responsable de site minier'), ('ENGINEER', 'Ingénieur sur le terrain'), ('MANAGER', 'Gestionnaire (zone/projet/exploitation)'), ('ANALYST', 'Analyste (données/performance/risques)'), ('STOCK_MANAGER', 'Gestionnaire de stock'), ('MMG', 'MMG – Ministère des Mines et de la Géologie')], default='ENGINEER', max_length=50),
        ),
    ]
