# Generated by Django 4.2.27 on 2026-02-07 10:25

from django.db import migrations


def migrate_role_values(apps, schema_editor):
    """
    Migrer les anciennes valeurs de rôle vers les nouvelles:
    - SUPERVISOR → SITE_MANAGER
    - OPERATOR → ENGINEER
    - OWNER → MANAGER
    - ADMIN, ANALYST, MMG restent inchangés
    """
    User = apps.get_model('accounts', 'User')
    
    # Mapping des anciennes valeurs vers les nouvelles
    role_mapping = {
        'SUPERVISOR': 'SITE_MANAGER',
        'OPERATOR': 'ENGINEER',
        'OWNER': 'MANAGER',
    }
    
    for old_role, new_role in role_mapping.items():
        User.objects.filter(role=old_role).update(role=new_role)
        print(f"Migrated {old_role} → {new_role}")


def reverse_migrate_role_values(apps, schema_editor):
    """
    Fonction inverse pour rollback:
    - SITE_MANAGER → SUPERVISOR
    - ENGINEER → OPERATOR
    - MANAGER → OWNER
    """
    User = apps.get_model('accounts', 'User')
    
    reverse_mapping = {
        'SITE_MANAGER': 'SUPERVISOR',
        'ENGINEER': 'OPERATOR',
        'MANAGER': 'OWNER',
    }
    
    for new_role, old_role in reverse_mapping.items():
        User.objects.filter(role=new_role).update(role=old_role)
        print(f"Reversed {new_role} → {old_role}")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_update_user_roles'),
    ]

    operations = [
        migrations.RunPython(migrate_role_values, reverse_migrate_role_values),
    ]
