# Generated by Django 4.2.27 on 2026-02-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_migrate_existing_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur de la plateforme'), ('SITE_MANAGER', 'Responsable de site minier'), ('SUPERVISOR', 'Gestionnaire de Site'), ('OPERATOR', 'Technicien/Opérateur'), ('ANALYST', 'Analyste'), ('OWNER', 'Propriétaire/Décideur'), ('MMG', 'Autorité (MMG)')], default='OPERATOR', max_length=50),
        ),
    ]
