# Generated by Django 4.2.27 on 2026-02-07 11:23

from django.db import migrations


def reverse_role_renames(apps, schema_editor):
    """
    La migration 0008 avait renommé à tort:
      SUPERVISOR → SITE_MANAGER
      OPERATOR → ENGINEER
      OWNER → MANAGER

    On restaure les valeurs originales.
    Note: SITE_MANAGER existait pas avant, donc tout utilisateur
    actuellement SITE_MANAGER est un ancien SUPERVISOR.
    """
    User = apps.get_model('accounts', 'User')

    # SITE_MANAGER → SUPERVISOR (c'étaient des SUPERVISOR avant)
    count = User.objects.filter(role='SITE_MANAGER').update(role='SUPERVISOR')
    if count:
        print(f"  Reverted {count} SITE_MANAGER → SUPERVISOR")

    # ENGINEER → OPERATOR
    count = User.objects.filter(role='ENGINEER').update(role='OPERATOR')
    if count:
        print(f"  Reverted {count} ENGINEER → OPERATOR")

    # MANAGER → OWNER
    count = User.objects.filter(role='MANAGER').update(role='OWNER')
    if count:
        print(f"  Reverted {count} MANAGER → OWNER")

    # STOCK_MANAGER → OPERATOR (si quelqu'un a été créé avec ce rôle)
    count = User.objects.filter(role='STOCK_MANAGER').update(role='OPERATOR')
    if count:
        print(f"  Reverted {count} STOCK_MANAGER → OPERATOR")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_fix_roles_restore_originals'),
    ]

    operations = [
        migrations.RunPython(reverse_role_renames, noop),
    ]
