# Generated by Django 4.2.27 on 2026-02-07 12:19

from django.db import migrations


def migrate_owner_to_site_manager(apps, schema_editor):
    """Convertir tous les utilisateurs OWNER → SITE_MANAGER"""
    User = apps.get_model('accounts', 'User')
    count = User.objects.filter(role='OWNER').update(role='SITE_MANAGER')
    if count:
        print(f"\n  → Converted {count} OWNER user(s) to SITE_MANAGER")


def reverse_migration(apps, schema_editor):
    """Reverse: pas possible de savoir qui était OWNER, on ne fait rien"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_owner_role'),
    ]

    operations = [
        migrations.RunPython(migrate_owner_to_site_manager, reverse_migration),
    ]
