# Generated by Django 4.2.27 on 2026-02-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auditlog_lockedstatus'),
        ('accounts', '0012_migrate_owner_to_site_manager'),
    ]

    operations = [
    ]
