# Generated by Django 4.2.27 on 2026-02-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_merge_20260221_1135'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_content_4b4dd4_idx',
            old_name='accounts_aud_content_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_user_id_d4cccd_idx',
            old_name='accounts_aud_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_action_11cc52_idx',
            old_name='accounts_aud_action_ts_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.CharField(help_text='Ex: reports.Report, operations.Operation', max_length=100, verbose_name='Type de contenu'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lockedstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('SITE_MANAGER', 'Gestionnaire de site'), ('TECHNICIEN', 'Technicien/Ingénieur'), ('ANALYST', 'Analyste/Décideur'), ('MMG', 'Autorité MMG')], default='TECHNICIEN', max_length=50),
        ),
    ]
