# Generated by Django 4.2.27 on 2026-02-03 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0002_operation_gps_latitude_operation_gps_longitude_and_more'),
        ('mining_sites', '0002_miningsite_code_miningsite_concession_geojson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code emplacement')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Capacité maximale (tonnes)')),
                ('location_type', models.CharField(choices=[('PIT', 'Fosse'), ('STOCKPILE', 'Terril/Stock'), ('WAREHOUSE', 'Entrepôt'), ('LOADING_ZONE', 'Zone de chargement'), ('PORT', 'Port/Terminal')], default='STOCKPILE', max_length=20, verbose_name="Type d'emplacement")),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude GPS')),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude GPS')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_locations', to='mining_sites.miningsite', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Emplacement de stockage',
                'verbose_name_plural': 'Emplacements de stockage',
                'ordering': ['site', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_code', models.CharField(max_length=50, unique=True, verbose_name='Code mouvement')),
                ('movement_type', models.CharField(choices=[('INITIAL', 'Stock initial'), ('EXTRACTION', 'Extraction'), ('EXPEDITION', 'Expédition'), ('TRANSFER_IN', 'Transfert entrant'), ('TRANSFER_OUT', 'Transfert sortant'), ('ADJUSTMENT', 'Ajustement inventaire'), ('LOSS', 'Perte/Déchet')], max_length=20, verbose_name='Type de mouvement')),
                ('mineral_type', models.CharField(choices=[('BAUXITE', 'Bauxite'), ('IRON', 'Fer'), ('GOLD', 'Or'), ('DIAMOND', 'Diamant'), ('MANGANESE', 'Manganèse'), ('URANIUM', 'Uranium'), ('OTHER', 'Autre')], default='BAUXITE', max_length=20, verbose_name='Type de minerai')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité (tonnes)')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Grade/Teneur (%)')),
                ('date', models.DateField(verbose_name='Date du mouvement')),
                ('destination', models.CharField(blank=True, max_length=255, verbose_name='Destination (client/port)')),
                ('transport_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence transport')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='stock.stocklocation', verbose_name='Emplacement destination')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='stock.stocklocation', verbose_name='Emplacement')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='operations.operation', verbose_name='Opération liée')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mineral_type', models.CharField(choices=[('BAUXITE', 'Bauxite'), ('IRON', 'Fer'), ('GOLD', 'Or'), ('DIAMOND', 'Diamant'), ('MANGANESE', 'Manganèse'), ('URANIUM', 'Uranium'), ('OTHER', 'Autre')], max_length=20, verbose_name='Type de minerai')),
                ('initial_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Stock initial')),
                ('total_extracted', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total extrait')),
                ('total_expedited', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total expédié')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Stock actuel')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_summaries', to='mining_sites.miningsite', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Synthèse stock',
                'verbose_name_plural': 'Synthèses stock',
                'unique_together': {('site', 'mineral_type')},
            },
        ),
    ]
