# Generated by Django 4.2.27 on 2026-01-20 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mining_sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('THRESHOLD_EXCEEDED', 'Seuil dépassé'), ('SAFETY', 'Sécurité'), ('MAINTENANCE', 'Maintenance requise'), ('ENVIRONMENTAL', 'Environnement'), ('PRODUCTION', 'Production'), ('SYSTEM', 'Système')], default='SYSTEM', max_length=20, verbose_name="Type d'alerte")),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('NEW', 'Nouvelle'), ('READ', 'Lue'), ('IN_PROGRESS', 'En cours de traitement'), ('RESOLVED', 'Résolue'), ('ARCHIVED', 'Archivée')], default='NEW', max_length=20, verbose_name='Statut')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Assignée à')),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='analytics.indicator', verbose_name='Indicateur lié')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='mining_sites.miningsite', verbose_name='Site concerné')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-generated_at'],
            },
        ),
    ]
