# Generated by Django 4.2.27 on 2026-02-03 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mining_sites', '0002_miningsite_code_miningsite_concession_geojson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('environment', '0002_environmentaldata_alert_generated_and_more'),
        ('incidents', '0002_incident_alert_sent_incident_alert_sent_at_and_more'),
        ('equipment', '0002_equipment_capacity_equipment_capacity_unit_and_more'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='priority',
        ),
        migrations.AddField(
            model_name='alert',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email envoyé'),
        ),
        migrations.AddField(
            model_name='alert',
            name='push_sent',
            field=models.BooleanField(default=False, verbose_name='Push envoyé'),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_environmental_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='environment.environmentaldata', verbose_name='Donnée environnementale liée'),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='equipment.equipment', verbose_name='Équipement lié'),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='incidents.incident', verbose_name='Incident lié'),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolution_notes',
            field=models.TextField(blank=True, verbose_name='Notes de résolution'),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par'),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=20, verbose_name='Gravité'),
        ),
        migrations.AddField(
            model_name='alert',
            name='sms_sent',
            field=models.BooleanField(default=False, verbose_name='SMS envoyé'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('THRESHOLD_EXCEEDED', 'Seuil dépassé'), ('SAFETY', 'Sécurité'), ('MAINTENANCE', 'Maintenance requise'), ('ENVIRONMENTAL', 'Environnement'), ('PRODUCTION', 'Production'), ('INCIDENT', 'Incident'), ('EQUIPMENT', 'Équipement'), ('STOCK', 'Stock'), ('SYSTEM', 'Système')], default='SYSTEM', max_length=20, verbose_name="Type d'alerte"),
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la règle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('alert_type', models.CharField(choices=[('THRESHOLD_EXCEEDED', 'Seuil dépassé'), ('SAFETY', 'Sécurité'), ('MAINTENANCE', 'Maintenance requise'), ('ENVIRONMENTAL', 'Environnement'), ('PRODUCTION', 'Production'), ('INCIDENT', 'Incident'), ('EQUIPMENT', 'Équipement'), ('STOCK', 'Stock'), ('SYSTEM', 'Système')], max_length=20, verbose_name="Type d'alerte à générer")),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=20, verbose_name='Gravité')),
                ('conditions', models.JSONField(default=dict, help_text="Conditions en format JSON pour déclencher l'alerte", verbose_name='Conditions')),
                ('notify_roles', models.JSONField(default=list, help_text="Liste des rôles: ['ADMIN', 'SUPERVISOR', ...]", verbose_name='Rôles à notifier')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notify_users', models.ManyToManyField(blank=True, related_name='alert_rules', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs à notifier')),
                ('sites', models.ManyToManyField(blank=True, related_name='alert_rules', to='mining_sites.miningsite', verbose_name='Sites concernés')),
            ],
            options={
                'verbose_name': "Règle d'alerte",
                'verbose_name_plural': "Règles d'alerte",
                'ordering': ['name'],
            },
        ),
    ]
