# Generated by Django 4.2.27 on 2026-02-20 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_add_notification_system'),
        ('alerts', '0002_remove_alert_priority_alert_email_sent_and_more'),
    ]

    operations = [
    ]
