# Generated by Django 4.2.27 on 2026-02-22 06:17

import alerts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0003_merge_20260220_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotificationpreferences',
            options={'verbose_name': 'Préférences de notification', 'verbose_name_plural': 'Préférences de notification'},
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usernotificationpreferences',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('OPERATIONAL', 'Opérationnel'), ('SAFETY', 'Sécurité'), ('MAINTENANCE', 'Maintenance'), ('ENVIRONMENTAL', 'Environnemental'), ('TECHNICAL', 'Technique'), ('ADMINISTRATIVE', 'Administratif')], db_index=True, default='TECHNICAL', max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, help_text='Utilisée pour regrouper les alertes identiques', max_length=255, null=True, verbose_name='Clé de déduplication'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de rejet'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Rejetée par'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_dismissed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Rejetée'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='priority_order',
            field=models.IntegerField(db_index=True, default=0, help_text='Plus élevé = priorité plus élevée', verbose_name='Ordre de priorité'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], db_index=True, default='MEDIUM', max_length=20, verbose_name='Gravité'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name="En attente jusqu'à"),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouvelle'), ('READ', 'Lue'), ('IN_PROGRESS', 'En cours de traitement'), ('RESOLVED', 'Résolue'), ('ARCHIVED', 'Archivée'), ('DISMISSED', 'Rejetée'), ('SNOOZED', 'En attente')], db_index=True, default='NEW', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='alerts_per_page',
            field=models.IntegerField(default=20, verbose_name='Alertes par page'),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='default_snooze_minutes',
            field=models.IntegerField(default=30, verbose_name='Durée de snooze par défaut (min)'),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='email_on_critical',
            field=models.BooleanField(default=True, verbose_name='Email sur critique'),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='enabled_alert_types',
            field=models.JSONField(default=list, help_text="['THRESHOLD_EXCEEDED', 'SAFETY', ...]", verbose_name="Types d'alertes"),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='enabled_categories',
            field=models.JSONField(default=list, help_text="['OPERATIONAL', 'SAFETY', ...]", verbose_name='Catégories activées'),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='enabled_severity_levels',
            field=models.JSONField(default=alerts.models.default_severity_levels, help_text="['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']", verbose_name='Niveaux de gravité'),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='group_by_category',
            field=models.BooleanField(default=True, verbose_name='Grouper par catégorie'),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='group_by_site',
            field=models.BooleanField(default=True, verbose_name='Grouper par site'),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='max_alerts_per_day',
            field=models.IntegerField(default=500, help_text='0 = pas de limite', verbose_name='Max alertes par jour'),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='max_alerts_per_hour',
            field=models.IntegerField(default=100, help_text='0 = pas de limite', verbose_name='Max alertes par heure'),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='push_notifications',
            field=models.BooleanField(default=True, verbose_name='Notifications push'),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='sms_on_critical',
            field=models.BooleanField(default=False, verbose_name='SMS sur critique'),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
