# Generated by Django 4.2.27 on 2026-01-20 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mining_sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre du rapport')),
                ('report_type', models.CharField(choices=[('DAILY', 'Rapport journalier'), ('WEEKLY', 'Rapport hebdomadaire'), ('MONTHLY', 'Rapport mensuel'), ('QUARTERLY', 'Rapport trimestriel'), ('ANNUAL', 'Rapport annuel'), ('INCIDENT', "Rapport d'incident"), ('ENVIRONMENTAL', 'Rapport environnemental'), ('CUSTOM', 'Rapport personnalisé')], default='MONTHLY', max_length=20, verbose_name='Type de rapport')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('GENERATED', 'Généré'), ('VALIDATED', 'Validé'), ('PUBLISHED', 'Publié')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('period_start', models.DateField(verbose_name='Début de période')),
                ('period_end', models.DateField(verbose_name='Fin de période')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Fichier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='mining_sites.miningsite', verbose_name='Site concerné')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-created_at'],
            },
        ),
    ]
