# Generated by Django 4.2.27 on 2026-02-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_APPROVAL', "En attente d'approbation"), ('GENERATED', 'Généré'), ('VALIDATED', 'Validé'), ('PUBLISHED', 'Publié')], default='DRAFT', max_length=20, verbose_name='Statut'),
        ),
    ]
