# Generated by Django 4.2.27 on 2026-01-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mining_sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_code', models.CharField(max_length=50, unique=True, verbose_name='Code équipement')),
                ('name', models.CharField(max_length=200, verbose_name='Nom/Désignation')),
                ('equipment_type', models.CharField(choices=[('TRUCK', 'Camion'), ('EXCAVATOR', 'Pelle excavatrice'), ('LOADER', 'Chargeuse'), ('DRILL', 'Foreuse'), ('CRUSHER', 'Concasseur'), ('CONVEYOR', 'Convoyeur'), ('PUMP', 'Pompe'), ('GENERATOR', 'Générateur'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name="Type d'équipement")),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Opérationnel'), ('MAINTENANCE', 'En maintenance'), ('BREAKDOWN', 'En panne'), ('RETIRED', 'Hors service')], default='OPERATIONAL', max_length=20, verbose_name='État')),
                ('commissioning_date', models.DateField(blank=True, null=True, verbose_name='Date de mise en service')),
                ('manufacturer', models.CharField(blank=True, max_length=150, verbose_name='Fabricant')),
                ('model', models.CharField(blank=True, max_length=150, verbose_name='Modèle')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de série')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='mining_sites.miningsite', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['equipment_code'],
            },
        ),
    ]
