# Generated by Django 4.2.27 on 2026-02-03 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En tonnes pour camions, m³ pour excavateurs, etc.', max_digits=10, null=True, verbose_name='Capacité'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='capacity_unit',
            field=models.CharField(blank=True, max_length=20, verbose_name='Unité de capacité'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='fuel_consumption_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Consommation carburant (L/h)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='hours_operated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Heures de fonctionnement'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dernière maintenance'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Prochaine maintenance prévue'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='qr_code',
            field=models.CharField(blank=True, help_text='Code unique pour scan mobile', max_length=200, null=True, unique=True, verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='year_of_manufacture',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de fabrication'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code équipement (ID unique)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('OPERATIONAL', 'Opérationnel'), ('MAINTENANCE', 'En maintenance'), ('BREAKDOWN', 'En panne'), ('RETIRED', 'Hors service')], default='OPERATIONAL', max_length=20, verbose_name='État opérationnel'),
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_code', models.CharField(max_length=50, unique=True, verbose_name='Code maintenance')),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Maintenance préventive'), ('CORRECTIVE', 'Maintenance corrective'), ('INSPECTION', 'Inspection'), ('OVERHAUL', 'Révision générale'), ('REPAIR', 'Réparation')], default='PREVENTIVE', max_length=20, verbose_name='Type de maintenance')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifiée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='SCHEDULED', max_length=20, verbose_name='Statut')),
                ('scheduled_date', models.DateField(verbose_name='Date prévue')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('description', models.TextField(verbose_name='Description des travaux')),
                ('findings', models.TextField(blank=True, verbose_name='Constatations')),
                ('actions_taken', models.TextField(blank=True, verbose_name='Actions réalisées')),
                ('parts_replaced', models.TextField(blank=True, verbose_name='Pièces remplacées')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Coût (GNF)')),
                ('hours_at_maintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Heures compteur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.equipment', verbose_name='Équipement')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_performed', to=settings.AUTH_USER_MODEL, verbose_name='Réalisé par')),
            ],
            options={
                'verbose_name': 'Historique de maintenance',
                'verbose_name_plural': 'Historique des maintenances',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
