# Generated by Django 4.2.27 on 2026-02-04 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_capacity_equipment_capacity_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En tonnes pour camions, m³ pour excavateurs, etc.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacité'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='fuel_consumption_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Consommation carburant (L/h)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hours_operated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Heures de fonctionnement'),
        ),
    ]
