# Generated by Django 4.2.27 on 2026-02-24 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipment_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='current_speed',
            field=models.FloatField(default=0.0, verbose_name='Vitesse actuelle (km/h)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Dernière Latitude connue'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Dernière Longitude connue'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_position_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horodatage position'),
        ),
        migrations.CreateModel(
            name='EquipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Tracking Équipement',
                'verbose_name_plural': 'Tracking Équipements',
                'ordering': ['-timestamp'],
            },
        ),
    ]
