# Generated by Django 4.2.27 on 2026-01-20 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        ('mining_sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_code', models.CharField(max_length=50, unique=True, verbose_name='Code opération')),
                ('operation_type', models.CharField(choices=[('EXTRACTION', 'Extraction'), ('DRILLING', 'Forage'), ('BLASTING', 'Dynamitage'), ('TRANSPORT', 'Transport'), ('PROCESSING', 'Traitement'), ('MAINTENANCE', 'Maintenance'), ('INSPECTION', 'Inspection'), ('OTHER', 'Autre')], default='EXTRACTION', max_length=20, verbose_name="Type d'opération")),
                ('date', models.DateField(verbose_name="Date de l'opération")),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifiée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PLANNED', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quantity_extracted', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Quantité extraite (tonnes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('equipment', models.ManyToManyField(blank=True, related_name='operations', to='equipment.equipment', verbose_name='Équipements utilisés')),
                ('personnel', models.ManyToManyField(blank=True, related_name='operations', to='personnel.personnel', verbose_name='Personnel impliqué')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='mining_sites.miningsite', verbose_name='Site')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_operations', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Opération minière',
                'verbose_name_plural': 'Opérations minières',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
