# Generated by Django 4.2.27 on 2026-02-03 15:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mining_sites', '0002_miningsite_code_miningsite_concession_geojson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0002_certification_personnel_contract_end_date_and_more'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude GPS'),
        ),
        migrations.AddField(
            model_name='operation',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude GPS'),
        ),
        migrations.AddField(
            model_name='operation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='operations_photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='operation',
            name='quantity_processed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Quantité traitée (tonnes)'),
        ),
        migrations.AddField(
            model_name='operation',
            name='quantity_transported',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Quantité transportée (tonnes)'),
        ),
        migrations.AddField(
            model_name='operation',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motif de rejet'),
        ),
        migrations.AddField(
            model_name='operation',
            name='validation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='operation',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'En attente de validation'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=20, verbose_name='Statut de validation'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('EXTRACTION', 'Extraction'), ('DRILLING', 'Forage'), ('BLASTING', 'Dynamitage'), ('TRANSPORT', 'Transport'), ('PROCESSING', 'Traitement'), ('LOADING', 'Chargement'), ('UNLOADING', 'Déchargement'), ('EXPEDITION', 'Expédition'), ('MAINTENANCE', 'Maintenance'), ('INSPECTION', 'Inspection'), ('OTHER', 'Autre')], default='EXTRACTION', max_length=20, verbose_name="Type d'opération"),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planifiée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PLANNED', max_length=20, verbose_name='Statut opérationnel'),
        ),
        migrations.CreateModel(
            name='WorkZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code zone')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la zone')),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude GPS')),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude GPS')),
                ('zone_geojson', models.JSONField(blank=True, help_text="Format: {'type': 'Polygon', 'coordinates': [[[lng, lat], ...]]}", null=True, verbose_name='Polygone zone (GeoJSON)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_zones', to='mining_sites.miningsite', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Zone de chantier',
                'verbose_name_plural': 'Zones de chantier',
                'ordering': ['site', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('shift_type', models.CharField(choices=[('DAY', 'Jour (6h-18h)'), ('NIGHT', 'Nuit (18h-6h)'), ('MORNING', 'Matin (6h-14h)'), ('AFTERNOON', 'Après-midi (14h-22h)'), ('EVENING', 'Soir (22h-6h)')], default='DAY', max_length=20, verbose_name='Type de rotation')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personnel', models.ManyToManyField(blank=True, related_name='shifts', to='personnel.personnel', verbose_name='Personnel affecté')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='mining_sites.miningsite', verbose_name='Site')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_shifts', to='personnel.personnel', verbose_name='Chef de poste')),
            ],
            options={
                'verbose_name': 'Rotation',
                'verbose_name_plural': 'Rotations',
                'ordering': ['-date', 'shift_type'],
                'unique_together': {('site', 'date', 'shift_type')},
            },
        ),
        migrations.CreateModel(
            name='OperationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='operations_photos/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Prise le')),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude GPS')),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude GPS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='operations.operation', verbose_name='Opération')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': "Photo d'opération",
                'verbose_name_plural': "Photos d'opérations",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='operations.shift', verbose_name='Rotation'),
        ),
        migrations.AddField(
            model_name='operation',
            name='work_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='operations.workzone', verbose_name='Zone de chantier'),
        ),
    ]
