# Generated by Django 4.2.27 on 2026-02-04 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_operation_gps_latitude_operation_gps_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='quantity_extracted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité extraite (tonnes)'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='quantity_processed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité traitée (tonnes)'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='quantity_transported',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité transportée (tonnes)'),
        ),
    ]
