# Generated by Django 4.2.27 on 2026-01-20 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mining_sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_code', models.CharField(max_length=50, unique=True, verbose_name='Code incident')),
                ('incident_type', models.CharField(choices=[('ACCIDENT', 'Accident corporel'), ('EQUIPMENT_FAILURE', 'Panne équipement'), ('ENVIRONMENTAL', 'Incident environnemental'), ('SECURITY', 'Incident de sécurité'), ('LANDSLIDE', 'Glissement de terrain'), ('FIRE', 'Incendie'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name="Type d'incident")),
                ('date', models.DateField(verbose_name="Date de l'incident")),
                ('time', models.TimeField(blank=True, null=True, verbose_name="Heure de l'incident")),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='LOW', max_length=20, verbose_name='Gravité')),
                ('status', models.CharField(choices=[('REPORTED', 'Déclaré'), ('INVESTIGATING', 'En investigation'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Clôturé')], default='REPORTED', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('actions_taken', models.TextField(blank=True, verbose_name='Actions prises')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Déclaré par')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='mining_sites.miningsite', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
