# Generated by Django 4.2.27 on 2026-02-03 15:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_capacity_equipment_capacity_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0002_certification_personnel_contract_end_date_and_more'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='alert_sent',
            field=models.BooleanField(default=False, verbose_name='Alerte envoyée'),
        ),
        migrations.AddField(
            model_name='incident',
            name='alert_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi de l'alerte"),
        ),
        migrations.AddField(
            model_name='incident',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture'),
        ),
        migrations.AddField(
            model_name='incident',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Clôturé par'),
        ),
        migrations.AddField(
            model_name='incident',
            name='contributing_factors',
            field=models.TextField(blank=True, verbose_name='Facteurs contributifs'),
        ),
        migrations.AddField(
            model_name='incident',
            name='corrective_actions',
            field=models.TextField(blank=True, verbose_name='Actions correctives planifiées'),
        ),
        migrations.AddField(
            model_name='incident',
            name='equipment_involved',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='equipment.equipment', verbose_name='Équipements impliqués'),
        ),
        migrations.AddField(
            model_name='incident',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Coût estimé (GNF)'),
        ),
        migrations.AddField(
            model_name='incident',
            name='fatalities_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de décès'),
        ),
        migrations.AddField(
            model_name='incident',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude GPS'),
        ),
        migrations.AddField(
            model_name='incident',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude GPS'),
        ),
        migrations.AddField(
            model_name='incident',
            name='injuries_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de blessés'),
        ),
        migrations.AddField(
            model_name='incident',
            name='investigated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Enquêté par'),
        ),
        migrations.AddField(
            model_name='incident',
            name='location_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Localisation (description)'),
        ),
        migrations.AddField(
            model_name='incident',
            name='lost_work_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Jours de travail perdus'),
        ),
        migrations.AddField(
            model_name='incident',
            name='personnel_involved',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='personnel.personnel', verbose_name='Personnel impliqué'),
        ),
        migrations.AddField(
            model_name='incident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='incidents_photos/', verbose_name='Photo principale'),
        ),
        migrations.AddField(
            model_name='incident',
            name='preventive_measures',
            field=models.TextField(blank=True, verbose_name='Mesures préventives'),
        ),
        migrations.AddField(
            model_name='incident',
            name='root_cause',
            field=models.TextField(blank=True, verbose_name='Cause racine'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('ACCIDENT', 'Accident corporel'), ('NEAR_MISS', "Presqu'accident"), ('EQUIPMENT_FAILURE', 'Panne équipement'), ('ENVIRONMENTAL', 'Incident environnemental'), ('SECURITY', 'Incident de sécurité'), ('LANDSLIDE', 'Glissement de terrain'), ('FIRE', 'Incendie'), ('EXPLOSION', 'Explosion'), ('CHEMICAL_SPILL', 'Déversement chimique'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name="Type d'incident"),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Déclaré'), ('INVESTIGATING', 'En investigation'), ('ACTION_REQUIRED', 'Action requise'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Clôturé')], default='REPORTED', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='IncidentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='incidents_photos/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Prise le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='incidents.incident', verbose_name='Incident')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': "Photo d'incident",
                'verbose_name_plural': "Photos d'incidents",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_description', models.TextField(verbose_name="Description de l'action")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('OVERDUE', 'En retard')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('due_date', models.DateField(verbose_name='Date limite')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_follow_ups', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='incidents.incident', verbose_name='Incident')),
            ],
            options={
                'verbose_name': "Suivi d'incident",
                'verbose_name_plural': "Suivis d'incidents",
                'ordering': ['due_date'],
            },
        ),
    ]
