# Generated by Django 4.2.27 on 2026-01-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiningSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du site')),
                ('location', models.CharField(max_length=500, verbose_name='Localisation')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('site_type', models.CharField(choices=[('OPEN_PIT', 'Ciel ouvert'), ('UNDERGROUND', 'Souterrain'), ('ALLUVIAL', 'Alluvionnaire'), ('MIXED', 'Mixte')], default='OPEN_PIT', max_length=20, verbose_name='Type de site')),
                ('status', models.CharField(choices=[('ACTIVE', 'En exploitation'), ('SUSPENDED', 'Suspendu'), ('CLOSED', 'Fermé'), ('EXPLORATION', 'En exploration')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site minier',
                'verbose_name_plural': 'Sites miniers',
                'ordering': ['name'],
            },
        ),
    ]
