# Generated by Django 4.2.27 on 2026-02-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningsite',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code du site'),
        ),
        migrations.AddField(
            model_name='miningsite',
            name='concession_geojson',
            field=models.JSONField(blank=True, help_text='Définit les limites géographiques de la concession minière', null=True, verbose_name='Polygone de concession (GeoJSON)'),
        ),
        migrations.AddField(
            model_name='miningsite',
            name='license_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'obtention de la licence"),
        ),
        migrations.AddField(
            model_name='miningsite',
            name='license_expiry',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration de la licence"),
        ),
        migrations.AddField(
            model_name='miningsite',
            name='mineral_type',
            field=models.CharField(choices=[('BAUXITE', 'Bauxite'), ('IRON', 'Fer'), ('GOLD', 'Or'), ('DIAMOND', 'Diamant'), ('MANGANESE', 'Manganèse'), ('URANIUM', 'Uranium'), ('OTHER', 'Autre')], default='BAUXITE', max_length=20, verbose_name='Type de minerai'),
        ),
        migrations.AddField(
            model_name='miningsite',
            name='operator_name',
            field=models.CharField(blank=True, help_text='Ex: CBG, GAC, SMB, etc.', max_length=200, verbose_name="Nom de l'opérateur"),
        ),
        migrations.AddField(
            model_name='miningsite',
            name='prefecture',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Préfecture'),
        ),
        migrations.AddField(
            model_name='miningsite',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Région administrative'),
        ),
        migrations.AddField(
            model_name='miningsite',
            name='surface_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Superficie (hectares)'),
        ),
        migrations.AlterField(
            model_name='miningsite',
            name='location',
            field=models.CharField(max_length=500, verbose_name='Localisation détaillée'),
        ),
    ]
