# Generated by Django 4.2.27 on 2026-02-24 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mining_sites', '0002_miningsite_code_miningsite_concession_geojson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningsite',
            name='geological_reserve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Réserve géologique estimée (tonnes)'),
        ),
        migrations.AddField(
            model_name='miningsite',
            name='geology_risk_index',
            field=models.IntegerField(default=0, help_text="Calculé par l'IA basée sur les sols et l'humidité", verbose_name='Index de risque géologique (0-100)'),
        ),
        migrations.CreateModel(
            name='DistributedNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100, unique=True, verbose_name='Identifiant du nœud')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP locale')),
                ('status', models.CharField(choices=[('ONLINE', 'En ligne'), ('OFFLINE', 'Hors ligne'), ('SYNCING', 'Synchronisation')], default='OFFLINE', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Dernière synchronisation')),
                ('cpu_usage', models.FloatField(default=0.0, verbose_name='Utilisation CPU (%)')),
                ('memory_usage', models.FloatField(default=0.0, verbose_name='Utilisation RAM (%)')),
                ('ai_model_version', models.CharField(default='v1.0-alpha', max_length=50)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distributed_node', to='mining_sites.miningsite', verbose_name='Site rattaché')),
            ],
            options={
                'verbose_name': 'Nœud Distribué',
                'verbose_name_plural': 'Nœuds Distribués',
            },
        ),
    ]
