# Generated by Django 4.2.27 on 2026-02-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining_sites', '0003_miningsite_geological_reserve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningsite',
            name='commissioning_date',
            field=models.DateField(blank=True, null=True, verbose_name='Mise en service du site'),
        ),
    ]
