# Generated by Django 4.2.27 on 2026-01-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mining_sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'indicateur")),
                ('indicator_type', models.CharField(choices=[('PRODUCTION', 'Production'), ('EFFICIENCY', 'Efficacité'), ('SAFETY', 'Sécurité'), ('ENVIRONMENTAL', 'Environnement'), ('EQUIPMENT', 'Équipement'), ('FINANCIAL', 'Financier')], default='PRODUCTION', max_length=20, verbose_name="Type d'indicateur")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('calculated_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Valeur calculée')),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Valeur cible')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unité')),
                ('threshold_warning', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name="Seuil d'alerte")),
                ('threshold_critical', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Seuil critique')),
                ('calculation_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de calcul')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='mining_sites.miningsite', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Indicateur',
                'verbose_name_plural': 'Indicateurs',
                'ordering': ['site', 'name'],
            },
        ),
    ]
