# Generated by Django 4.2.27 on 2026-01-20 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mining_sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('AIR_QUALITY', "Qualité de l'air"), ('WATER_QUALITY', "Qualité de l'eau"), ('NOISE_LEVEL', 'Niveau sonore'), ('DUST_LEVEL', 'Niveau de poussière'), ('PH_LEVEL', 'Niveau pH'), ('TEMPERATURE', 'Température'), ('HUMIDITY', 'Humidité'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Type de mesure')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valeur mesurée')),
                ('unit', models.CharField(max_length=20, verbose_name='Unité de mesure')),
                ('measurement_date', models.DateField(verbose_name='Date de mesure')),
                ('measurement_time', models.TimeField(blank=True, null=True, verbose_name='Heure de mesure')),
                ('location_details', models.CharField(blank=True, max_length=200, verbose_name='Emplacement précis')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_environmental_data', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='environmental_data', to='mining_sites.miningsite', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Donnée environnementale',
                'verbose_name_plural': 'Données environnementales',
                'ordering': ['-measurement_date', '-measurement_time'],
            },
        ),
    ]
