# Generated by Django 4.2.27 on 2026-02-03 15:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mining_sites', '0002_miningsite_code_miningsite_concession_geojson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentaldata',
            name='alert_generated',
            field=models.BooleanField(default=False, verbose_name='Alerte générée'),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude GPS'),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude GPS'),
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='is_compliant',
            field=models.BooleanField(default=True, verbose_name='Conforme aux seuils'),
        ),
        migrations.AlterField(
            model_name='environmentaldata',
            name='data_type',
            field=models.CharField(choices=[('AIR_QUALITY', "Qualité de l'air"), ('WATER_QUALITY', "Qualité de l'eau"), ('NOISE_LEVEL', 'Niveau sonore'), ('DUST_LEVEL', 'Niveau de poussière'), ('PH_LEVEL', 'Niveau pH'), ('TEMPERATURE', 'Température'), ('HUMIDITY', 'Humidité'), ('CO2_LEVEL', 'Niveau CO2'), ('PARTICULATE_MATTER', 'Particules fines'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Type de mesure'),
        ),
        migrations.CreateModel(
            name='EnvironmentalThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du seuil')),
                ('data_type', models.CharField(choices=[('AIR_QUALITY', "Qualité de l'air"), ('WATER_QUALITY', "Qualité de l'eau"), ('NOISE_LEVEL', 'Niveau sonore'), ('DUST_LEVEL', 'Niveau de poussière'), ('PH_LEVEL', 'Niveau pH'), ('TEMPERATURE', 'Température'), ('HUMIDITY', 'Humidité'), ('CO2_LEVEL', 'Niveau CO2'), ('PARTICULATE_MATTER', 'Particules fines'), ('OTHER', 'Autre')], max_length=20, verbose_name='Type de mesure')),
                ('threshold_type', models.CharField(choices=[('REGULATORY', 'Réglementaire'), ('INTERNAL', 'Interne'), ('WARNING', 'Avertissement')], default='INTERNAL', max_length=20, verbose_name='Type de seuil')),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Valeur minimale acceptable')),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Valeur maximale acceptable')),
                ('warning_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Seuil d'avertissement min")),
                ('warning_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="Seuil d'avertissement max")),
                ('unit', models.CharField(max_length=20, verbose_name='Unité de mesure')),
                ('regulatory_reference', models.CharField(blank=True, help_text='Ex: Code minier Art. 45, Norme ISO...', max_length=255, verbose_name='Référence réglementaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environmental_thresholds', to='mining_sites.miningsite', verbose_name='Site (vide = global)')),
            ],
            options={
                'verbose_name': 'Seuil environnemental',
                'verbose_name_plural': 'Seuils environnementaux',
                'ordering': ['data_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_period', models.CharField(choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('QUARTERLY', 'Trimestriel'), ('ANNUAL', 'Annuel')], default='MONTHLY', max_length=20, verbose_name='Période')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('total_measurements', models.PositiveIntegerField(default=0, verbose_name='Total des mesures')),
                ('compliant_count', models.PositiveIntegerField(default=0, verbose_name='Mesures conformes')),
                ('non_compliant_count', models.PositiveIntegerField(default=0, verbose_name='Mesures non conformes')),
                ('summary', models.TextField(blank=True, verbose_name='Résumé')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recommandations')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='environmental_reports/', verbose_name='Fichier du rapport')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_environmental_reports', to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='environmental_reports', to='mining_sites.miningsite', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Rapport environnemental',
                'verbose_name_plural': 'Rapports environnementaux',
                'ordering': ['-end_date'],
            },
        ),
        migrations.AddField(
            model_name='environmentaldata',
            name='threshold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='environment.environmentalthreshold', verbose_name='Seuil de référence'),
        ),
    ]
