# Generated by Django 4.2.27 on 2026-02-03 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mining_sites', '0002_miningsite_code_miningsite_concession_geojson_and_more'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la certification')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('issuing_authority', models.CharField(blank=True, max_length=200, verbose_name='Organisme délivrant')),
                ('validity_period_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée de validité (mois)')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de contrat'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name="Contact d'urgence"),
        ),
        migrations.AddField(
            model_name='personnel',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone d'urgence"),
        ),
        migrations.AddField(
            model_name='personnel',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='personnel_photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='role',
            field=models.CharField(choices=[('TECHNICIAN', 'Technicien'), ('ENGINEER', 'Ingénieur'), ('OPERATOR', "Opérateur d'engins"), ('DRIVER', 'Chauffeur'), ('SUPERVISOR', "Chef d'équipe"), ('HSE_OFFICER', 'Agent HSE'), ('MAINTENANCE', 'Agent de maintenance'), ('SECURITY', 'Agent de sécurité'), ('ADMIN', 'Administratif'), ('OTHER', 'Autre')], default='TECHNICIAN', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='mining_sites.miningsite', verbose_name="Site d'affectation actuel"),
        ),
        migrations.CreateModel(
            name='SiteAffectationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('position', models.CharField(max_length=150, verbose_name='Poste occupé')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motif du changement')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectation_history', to='personnel.personnel')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectation_history', to='mining_sites.miningsite')),
            ],
            options={
                'verbose_name': "Historique d'affectation",
                'verbose_name_plural': 'Historique des affectations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_date', models.DateField(verbose_name="Date d'obtention")),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de certificat')),
                ('document', models.FileField(blank=True, null=True, upload_to='certifications/', verbose_name='Document justificatif')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_certifications', to='personnel.certification')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_certifications', to='personnel.personnel')),
            ],
            options={
                'verbose_name': 'Certification du personnel',
                'verbose_name_plural': 'Certifications du personnel',
                'unique_together': {('personnel', 'certification')},
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='personnel', through='personnel.PersonnelCertification', to='personnel.certification', verbose_name='Certifications'),
        ),
    ]
