# Generated by Django 4.2.27 on 2026-02-09 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0002_certification_personnel_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation/refus"),
        ),
        migrations.AddField(
            model_name='personnel',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', "En attente d'approbation"), ('APPROVED', 'Approuvé'), ('REJECTED', 'Refusé')], default='PENDING', max_length=20, verbose_name="Statut d'approbation"),
        ),
        migrations.AddField(
            model_name='personnel',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_personnel', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé/Refusé par'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motif du refus'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_personnel', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par'),
        ),
    ]
